# Generated by Django 3.2.3 on 2021-05-17 18:03

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_uploads'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='images'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='photos.category'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='photos.location'),
        ),
    ]
